### ISSUE TITLE
test result trends in gitlab

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#847]
Currently unit test results are not shown in gitlab.
![image.png](https://images.zenhubusercontent.com/600ed297091d3ea152b83c2d/a0247793-93b4-4fe0-80b1-fb45264cba91)
It is possible to have show them in gitlab if the unit test report xml is created and made an "artifact"
![image.png](https://images.zenhubusercontent.com/600ed297091d3ea152b83c2d/d2b6cc00-e060-40ca-ac76-ff25124f5bfb)

code example for `gitlab-ci.yml`

```yaml
  artifacts:
    paths:
      - nosetests.xml
    reports:
      junit: nosetests.xml
```
